classes: {
  Con: {
    grid-rows: 3
    grid-columns: 1
    grid-gap: 10
    width: 210
    label: Container
  }
  w150: { width: 150; height: 40 }
  w470: { width: 470; height: 50 }
}

Containers {
  grid-rows: 3
  grid-gap: 10
  style: {
    font-color: "#fbfbfb"
    stroke: transparent
    fill: transparent
    text-transform: uppercase
  }
  # style.fill: "#fafafa"

  con1: {
    class: Con
    App.class: w150
    Bins/Libs.class: w150
  }

  con2: {
    class: Con
    App.class: w150
    Bins/Libs.class: w150
  }

  con3: {
    class: Con
    App.class: w150
    Bins/Libs.class: w150
  }

  Container Engine {
    class: w470
    style: {
      fill: "#BBEAF0"
    }
  }

  Host OS {
    class: w470
    style: {
      fill: "#E0C0E5"
    }
  }
}
